<?php

namespace MissionControl\Bundle\OviappBundle\Entity;

use Doctrine\ORM\Mapping as ORM;
use MissionControl\Bundle\UserBundle\Entity\User;

/**
 * ProdusRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProdusRepository extends \Doctrine\ORM\EntityRepository
{
}
